### ISSUE TITLE
Please provide unpackaged AppImage for download

### ISSUE THREAD

**Issue by probonopd** [philipborg/CubeShuffle#110]
Hello, could you please, instead of [CubeShuffle-GUI.AppImage.tar.gz](https://github.com/philipborg/CubeShuffle/releases/download/v0.1.0-beta.9/CubeShuffle-GUI.AppImage.tar.gz), provide an AppImage for download?

Reference:
https://github.com/AppImage/AppImageKit/wiki/Creating-AppImages/cc2441518975caca23e9ce2dba6f08a22c678d1e#common-mistake

**Comment by philipborg** [comment]
Sure. It's currently a tar.gz for Tauri auto-update but I can provide a non-tar.gz file as well.
